config/routes.rb
Rails.application.routes.draw do

  root to: 'articles#new'

  resources :schmarticles
  resources :articles, only: [ :new, :index, :create, :show, :edit, :update, :destroy ]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/schmarticle.rb
class Schmarticle < ApplicationRecord
end

app/models/shmarticle.rb
class Shmarticle < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.all
  end

  def show
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:notice] = "Article has been created!"
      redirect_to @article
    else
      flash.now[:alert] = "Whoopsie!"
      render :new
    end
  end

  def update
    if @article.update(article_params)
      flash.notice = "Success!"
      redirect_to @article
    else
      flash.now.alert = "Whoopsiedupskies..."
      render :edit
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :body)
  end

  def set_article
    @article = Article.find(params[:id])
  end
end

app/controllers/articles_controller_notes.rb
class ArticlesController < ApplicationController

  def new 

  end

  def create
    @article = Article.new(:title => "title", :body => "body")
      # Could one have instead: 
      # @article = Article.new params[:title, :body] OR
      # @article = Article.new(article_params) with private method   (see below) ?

    if @article.save
#     redirect_to @article  ... this is a short cut
      redirect_to article_path(@article.id)
    else
      render :new    # implicit so therefore don't really need?
    end
  end

  def show
    @article = Article.find(:title)
  end

end

'''

# ##############

  private
    def article_params
      params.require(:article).permit(:title, :body)
    end

# ############# standard CRUD ... delete when finished #############


class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new params[:post]
    if @post.save
      redirect_to posts_path
    else
      render :action => 'new'
    end
  end

  def edit
    @post = Post.find params[:id]
  end

  def update
    @post = Post.find params[:id]
    if @post.update_attributes params[:post]
      redirect_to posts_path
    else
      render :action => :edit
    end
  end

  def destroy
    @post = Post.find params[:id]
    @post.destroy
    redirect_to posts_path
  end

  def show
    @post = Post.find params[:id]
  end

end
# '''

app/controllers/schmarticles_controller.rb
class SchmarticlesController < ApplicationController
  before_action :set_schmarticle, only: [:show, :edit, :update, :destroy]

  def index
    @schmarticles = Schmarticle.all
  end

  def show
  end

  def new
    @schmarticle = Schmarticle.new
  end

  def edit
  end

  def create
    @schmarticle = Schmarticle.new(schmarticle_params)

    respond_to do |format|
      if @schmarticle.save
        format.html { redirect_to @schmarticle, notice: 'Schmarticle was successfully created.' }
        format.json { render :show, status: :created, location: @schmarticle }
      else
        format.html { render :new }
        format.json { render json: @schmarticle.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @schmarticle.update(schmarticle_params)
        format.html { redirect_to @schmarticle, notice: 'Schmarticle was successfully updated.' }
        format.json { render :show, status: :ok, location: @schmarticle }
      else
        format.html { render :edit }
        format.json { render json: @schmarticle.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @schmarticle.destroy
    respond_to do |format|
      format.html { redirect_to schmarticles_url, notice: 'Schmarticle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schmarticle
      @schmarticle = Schmarticle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def schmarticle_params
      params.require(:schmarticle).permit(:title, :body)
    end
end

app/controllers/shmarticles_controller.rb
class ShmarticlesController < ApplicationController
  before_action :set_shmarticle, only: [:show, :edit, :update, :destroy]

  # GET /shmarticles
  # GET /shmarticles.json
  def index
    @shmarticles = Shmarticle.all
  end

  # GET /shmarticles/1
  # GET /shmarticles/1.json
  def show
  end

  # GET /shmarticles/new
  def new
    @shmarticle = Shmarticle.new
  end

  # GET /shmarticles/1/edit
  def edit
  end

  # POST /shmarticles
  # POST /shmarticles.json
  def create
    @shmarticle = Shmarticle.new(shmarticle_params)

    respond_to do |format|
      if @shmarticle.save
        format.html { redirect_to @shmarticle, notice: 'Shmarticle was successfully created.' }
        format.json { render :show, status: :created, location: @shmarticle }
      else
        format.html { render :new }
        format.json { render json: @shmarticle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shmarticles/1
  # PATCH/PUT /shmarticles/1.json
  def update
    respond_to do |format|
      if @shmarticle.update(shmarticle_params)
        format.html { redirect_to @shmarticle, notice: 'Shmarticle was successfully updated.' }
        format.json { render :show, status: :ok, location: @shmarticle }
      else
        format.html { render :edit }
        format.json { render json: @shmarticle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shmarticles/1
  # DELETE /shmarticles/1.json
  def destroy
    @shmarticle.destroy
    respond_to do |format|
      format.html { redirect_to shmarticles_url, notice: 'Shmarticle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shmarticle
      @shmarticle = Shmarticle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shmarticle_params
      params.require(:shmarticle).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_helper.rb
module ArticleHelper

def article_params
  params.require(:article).permit(:title, :body)
end
end

app/helpers/articles_controller_helper.rb
module ArticlesControllerHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/schmarticles_helper.rb
module SchmarticlesHelper
end

app/helpers/shmarticles_helper.rb
module ShmarticlesHelper
end

app/helpers/your_controller_name_helper.rb
module YourControllerNameHelper
end

app/views/articles/_article.html.erb
<%# _article.html.erb %>


<li>
  <%= "#{article.title} ... #{article.body}" %>
  <%= link_to "Edit This Article", edit_article_path(article) %>
  <%= link_to "Delete This Article", article_path(article), method: :delete %>
</li>

app/views/articles/_article.html.slim
tr
  td = link_to article.id, article
  td = link_to article.title, article
  td = article.body
  td = link_to "Edit", edit_article_path(article)
  td = link_to "delete", article, method: :delete

app/views/articles/_article_form.html.erb
<%= form_for(@article) do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>

    <%= f.label :body %>
    <%= f.text_area :body %>

    <%= f.submit "Post Article" %>
<% end %>

app/views/articles/_article_header.html.slim
thead
  tr
    th Id
    th Title
    th Body
    th Edit
    th Delete

app/views/articles/_delete_link.html.erb
<p>

	<%= link_to 'DELETE', article_path( @article ), method: 'delete', class: "button" %>

</p>

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
<% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<p>
  <%= f.label :title %><br>
  <%= f.text_field :title %>
</p>
<p>
  <%= f.label :body %><br>
  <%= f.text_area :body %>
</p>
  <%= f.submit %>
<% end %> <!-- form_for :articles -->

app/views/articles/_nav.html.erb
<nav>
  <ul id="navbar">
  <li>
    <%= link_to 'all articles', root_path %>
    <%= link_to 'create new article', new_article_path %>
  </ul> 
</nav>

app/views/articles/edit.html.slim
h2 Edit article

= form_for @article do |f|
  div
    = f.label :title
    = f.text_field :title

  div
    = f.label :body
    = f.text_area :body

  = f.submit

app/views/articles/index.html.erb
<h1>Articles Index</h1>

<ul>
<% @articles.each do |article| %>
  <li><%= link_to article.title, article %> (<%= link_to article.id, article %>)  |  <%= link_to 'edit', edit_article_path(article) %> | <%= link_to 'delete', article, method: :delete, data: {confirm: "Really delete the article?"} %></li>
<% end %>
</ul>

app/views/articles/index.html.slim
table class="ui celled table"
  = render 'article_header'
  = render @articles

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render partial: 'form' %>

app/views/articles/new.html.slim
= form_for @article do |f|
  div
    = f.label :title
    = f.text_field :title

  div
    = f.label :body
    = f.text_area :body

  = f.submit

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<p><%= @article.body %></p>

<p><%= link_to 'edit', edit_article_path(@article) %> | <%= link_to 'delete', @article, method: :delete, data: {confirm: "Really delete the article?"} %></p>

app/views/articles/show.html.slim
table class="ui celled table"
  = render 'article_header'
  = render @article

app/views/common/_nav.html.erb
<ul>
  <%= link_to "Articles", articles_path %>
  <%= link_to "Create", new_article_path %>
</ul>

app/views/layouts/shared/_navbar_links.html.erb
<%# _navbar_links.html.erb %>

<%= link_to "Show All Articles", articles_path %>

<%= link_to "Crreate New Articles", new_article_path %>

app/views/schmarticles/_form.html.erb
<%= form_for(schmarticle) do |f| %>
  <% if schmarticle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(schmarticle.errors.count, "error") %> prohibited this schmarticle from being saved:</h2>

      <ul>
      <% schmarticle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schmarticles/edit.html.erb
<h1>Editing Schmarticle</h1>

<%= render 'form', schmarticle: @schmarticle %>

<%= link_to 'Show', @schmarticle %> |
<%= link_to 'Back', schmarticles_path %>

app/views/schmarticles/index.html.erb
<h1>Schmarticles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @schmarticles.each do |schmarticle| %>
      <tr>
        <td><%= schmarticle.title %></td>
        <td><%= schmarticle.body %></td>
        <td><%= link_to 'Show', schmarticle %></td>
        <td><%= link_to 'Edit', edit_schmarticle_path(schmarticle) %></td>
        <td><%= link_to 'Destroy', schmarticle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Schmarticle', new_schmarticle_path %>

app/views/schmarticles/new.html.erb
<h1>New Schmarticle</h1>

<%= render 'form', schmarticle: @schmarticle %>

<%= link_to 'Back', schmarticles_path %>

app/views/schmarticles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @schmarticle.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @schmarticle.body %>
</p>

<%= link_to 'Edit', edit_schmarticle_path(@schmarticle) %> |
<%= link_to 'Back', schmarticles_path %>

app/views/shared/_flash.html.erb
<% unless flash.empty? %>
	<% flash.each do |key, value| %>
	<p><%= value %></p>
  <% end %>
<% end %>

app/views/shared/_nav.html.erb
<nav>
  <ul>

    <li>
      <%= link_to "Index", articles_path %>
    </li>

    <li>
      <%= link_to "New", new_article_path %>
    </li>

  </ul>
</nav>

app/views/shared/_navbar.html.erb
<nav>
  <%= link_to 'home', root_path %> |
  <%= link_to 'new article', new_article_path %> |
  <%= link_to 'articles index', articles_path %> |
  <%= link_to 'new schmarticle', new_schmarticle_path %> |
  <%= link_to 'schmarticles index', schmarticles_path %>
</nav>

app/views/shared/_navbar_links.html.erb
<%# _navbar_links.html.erb %>

<%= link_to "Show All Articles", articles_path %>

<%= link_to "Create New Articles", new_article_path %>

app/views/shared/_navigation.html.erb
<nav>
	<%= link_to "View Articles",  articles_path  %>
	<%= link_to "Create new article", new_article_path %>
</nav>

app/views/shmarticles/_form.html.erb
<%= form_for(@shmarticle) do |f| %>
  <% if @shmarticle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shmarticle.errors.count, "error") %> prohibited this shmarticle from being saved:</h2>

      <ul>
      <% @shmarticle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shmarticles/edit.html.erb
<h1>Editing Shmarticle</h1>

<%= render 'form' %>

<%= link_to 'Show', @shmarticle %> |
<%= link_to 'Back', shmarticles_path %>

app/views/shmarticles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Shmarticles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shmarticles.each do |shmarticle| %>
      <tr>
        <td><%= shmarticle.title %></td>
        <td><%= shmarticle.body %></td>
        <td><%= link_to 'Show', shmarticle %></td>
        <td><%= link_to 'Edit', edit_shmarticle_path(shmarticle) %></td>
        <td><%= link_to 'Destroy', shmarticle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shmarticle', new_shmarticle_path %>

app/views/shmarticles/new.html.erb
<h1>New Shmarticle</h1>

<%= render 'form' %>

<%= link_to 'Back', shmarticles_path %>

app/views/shmarticles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @shmarticle.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @shmarticle.body %>
</p>

<%= link_to 'Edit', edit_shmarticle_path(@shmarticle) %> |
<%= link_to 'Back', shmarticles_path %>